In [25]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz        #draws the tree 
from sklearn.model_selection import train_test_split
import pydotplus

In [7]:
iris = pd.read_csv("C:/Users/KUMAR/Downloads/Iris.csv")

In [8]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [10]:
iris.isnull()

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [11]:
iris['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [12]:
df = iris.groupby('Species')

In [13]:
df.corr()

                                     Id  SepalLengthCm  SepalWidthCm  \
Species
Iris-setosa     Id             1.000000      -0.033561     -0.066688
                SepalLengthCm -0.033561       1.000000      0.746780
                SepalWidthCm  -0.066688       0.746780      1.000000
                PetalLengthCm  0.053253       0.263874      0.176695
                PetalWidthCm   0.087492       0.279092      0.279973
Iris-versicolor Id             1.000000      -0.269056     -0.081867
                SepalLengthCm -0.269056       1.000000      0.525911
                SepalWidthCm  -0.081867       0.525911      1.000000
                PetalLengthCm -0.189481       0.754049      0.560522
                PetalWidthCm  -0.168846       0.546461      0.663999
Iris-virginica  Id             1.000000      -0.012549      0.130884
                SepalLengthCm -0.012549       1.000000      0.457228
                SepalWidthCm   0.130884       0.457228      1.000000
                PetalLengthCm -0.204204       0.864225      0.401045
                PetalWidthCm   0.036446       0.281108      0.537728

                               PetalLengthCm  PetalWidthCm
Species
Iris-setosa     Id                  0.053253      0.087492
                SepalLengthCm       0.263874      0.279092
                SepalWidthCm        0.176695      0.279973
                PetalLengthCm       1.000000      0.306308
                PetalWidthCm        0.306308      1.000000
Iris-versicolor Id                 -0.189481     -0.168846
                SepalLengthCm       0.754049      0.546461
                SepalWidthCm        0.560522      0.663999
                PetalLengthCm       1.000000      0.786668
                PetalWidthCm        0.786668      1.000000
Iris-virginica  Id                 -0.204204      0.036446
                SepalLengthCm       0.864225      0.281108
                SepalWidthCm        0.401045      0.537728
                PetalLengthCm       1.000000      0.322108
                PetalWidthCm        0.322108      1.000000

In [14]:
#func to convert categorical data into numeric
def converter(s):
  s = s.lower()
  if s == 'iris-setosa':
    return 0
  elif s == 'iris-versicolor':
    return 1
  elif s == 'iris-virginica':
    return 2
  else:
    return -1

In [16]:
features = iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
labels = iris["Species"]

In [17]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size = 0.3)

In [18]:
#decision tree
model = DecisionTreeClassifier(criterion = "entropy", max_depth = 3, random_state = 42)
model.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=42)

In [19]:
model.predict(X_test)

array(['Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa'], dtype=object)

In [22]:
import graphviz
from sklearn import tree
#DOT data
dot_data = tree.export_graphviz(model, out_file = None,
                                feature_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width'],
                                class_names = "species",
                                filled = True)